// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoxqTfYDyuceejV66fQGckzOXI90KdhOE',
    appId: '1:1000216086557:web:e1812c3adc06b048c3def4',
    messagingSenderId: '1000216086557',
    projectId: 'blackwood-restaurant-app',
    authDomain: 'blackwood-restaurant-app.firebaseapp.com',
    storageBucket: 'blackwood-restaurant-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs4B6r4pOAO2UN2YUItoBFUmNkIbOBP38',
    appId: '1:1000216086557:android:b1bc30f28c9cc338c3def4',
    messagingSenderId: '1000216086557',
    projectId: 'blackwood-restaurant-app',
    storageBucket: 'blackwood-restaurant-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiwXeDGH-p7rCkV-o2g9tM4xjNTt7zw24',
    appId: '1:1000216086557:ios:bf5e8d903e6b625dc3def4',
    messagingSenderId: '1000216086557',
    projectId: 'blackwood-restaurant-app',
    storageBucket: 'blackwood-restaurant-app.firebasestorage.app',
    iosBundleId: 'com.example.blackwoodRestaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiwXeDGH-p7rCkV-o2g9tM4xjNTt7zw24',
    appId: '1:1000216086557:ios:bf5e8d903e6b625dc3def4',
    messagingSenderId: '1000216086557',
    projectId: 'blackwood-restaurant-app',
    storageBucket: 'blackwood-restaurant-app.firebasestorage.app',
    iosBundleId: 'com.example.blackwoodRestaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoxqTfYDyuceejV66fQGckzOXI90KdhOE',
    appId: '1:1000216086557:web:ffd712f05d379300c3def4',
    messagingSenderId: '1000216086557',
    projectId: 'blackwood-restaurant-app',
    authDomain: 'blackwood-restaurant-app.firebaseapp.com',
    storageBucket: 'blackwood-restaurant-app.firebasestorage.app',
  );
}
